# Generated by Django 5.0.3 on 2024-06-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_janr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='janr',
            name='name',
        ),
    ]
